# -*- coding: utf-8 -*-
"""Tests Unitaires

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EAEGhqzOh0jNqjB0C8UsIEn4yxkNRFyb
"""

import pytest
import json
from pathlib import Path
from src.core.metrics import MetricsManager, DailyStats, GlobalMetrics
from datetime import date

# Fixture pour isoler les tests du système de fichiers réel
@pytest.fixture
def temp_metrics_file(tmp_path):
    d = tmp_path / "data"
    d.mkdir()
    p = d / "test_metrics.json"
    return p

def test_initialization_creates_empty_metrics(temp_metrics_file):
    """Vérifie que le manager s'initialise correctement sans fichier."""
    manager = MetricsManager(storage_path=temp_metrics_file)
    assert isinstance(manager.data, GlobalMetrics)
    assert len(manager.data.history) == 0

def test_persistence_cycle(temp_metrics_file):
    """Vérifie l'écriture et la relecture après 'redémarrage'."""
    # 1. Init et écriture
    manager = MetricsManager(storage_path=temp_metrics_file)
    manager.record_operation(tokens=100, latency_ms=50.0)

    assert temp_metrics_file.exists()

    # 2. Simulation redémarrage (nouvelle instance)
    manager2 = MetricsManager(storage_path=temp_metrics_file)
    today_key = date.today().isoformat()

    assert today_key in manager2.data.history
    saved_day = manager2.data.history[today_key]
    assert saved_day.total_operations == 1
    assert saved_day.total_tokens_used == 100

def test_atomic_file_integrity(temp_metrics_file):
    """Vérifie que le fichier JSON est valide."""
    manager = MetricsManager(storage_path=temp_metrics_file)
    manager.record_operation(tokens=10, latency_ms=10.0)

    with open(temp_metrics_file, 'r') as f:
        content = json.load(f)

    assert "history" in content
    assert "version" in content

def test_corrupted_file_recovery(temp_metrics_file):
    """
    Protocol 02-AUDIT-FIRST:
    Le système doit survivre à un fichier corrompu et le sauvegarder.
    """
    # Création fichier corrompu
    with open(temp_metrics_file, 'w') as f:
        f.write("{ invalid json ...")

    manager = MetricsManager(storage_path=temp_metrics_file)

    # Le fichier original doit avoir été backupé
    backups = list(temp_metrics_file.parent.glob("*.corrupt.*.json"))
    assert len(backups) == 1

    # Le manager doit être reparti de zéro
    assert len(manager.data.history) == 0
    # Et doit être fonctionnel
    manager.record_operation(tokens=5, latency_ms=20)
    assert manager.data.history[date.today().isoformat()].total_operations == 1